# Publish this application to bluemix using ansible
---
- name: Publish the app to Bluemix
  hosts: localhost
  connection: local
  vars:
    date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M%S%Z')  }}"
    pipeline_id: "{{ lookup('env','PIPELINE_ID') | default('test-php-sample-1',true) }}"
    app_hostname: "{{ lookup('env','APP_HOSTNAME') | default(pipeline_id,true) }}"
    pwd: "{{ lookup('env', 'PWD') }}"
    s3_bucket: "{{ lookup('env', 'S3_BUCKET')  }}"
    #aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    #aws_secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
    # AWS_ACCESS_KEY && AWS_SECRET_KEY
  tasks:
    - name: debug
      debug:
        var: app_hostname
    - name: debug2
      debug:

    # Create archive for S3
    - name: Create Directory
      file:
        path: "{{ pwd }}/s3"
        state: directory
    - name: Create Archive
      shell: "tar -cvzf {{pwd}}/s3/{{app_hostname}}.tar -X .tarignore ."

    # ansible s3 docs: http://docs.ansible.com/ansible/s3_module.html
    - name: list apps
      elasticbeanstalk_version:
        app_name: test-app
        state: list
        region: us-west-2
    - name: upload version
      elasticbeanstalk_version:
        region: us-west-2
        app_name: "{{ app_hostname }}"
        version_label: "{{ date }}"
        s3_bucket: "{{ s3_bucket }}"
        s3_key: "{{pwd}}/s3/{{app_hostname}}.tar"
        state: present
      register: version

#    - name: Store Artifacts in S3
#      s3:
#        mode: put
#        bucket: "{{ s3_bucket }}"
#        src: "{{pwd}}/s3/{{app_hostname}}.tar"
#        object: "{{app_hostname}}.tar"
        #aws_access_key: "{{ aws_access_key }}"
        #aws_secret_key: "{{ aws_secret_key }}"
